# Generated by Django 4.2.1 on 2023-05-25 05:11

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic_id', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('tactic_name', models.CharField(max_length=250, verbose_name='Name')),
                ('tactic_description', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tactic_id'],
            },
        ),
    ]
