# Generated by Django 4.2.1 on 2023-05-19 06:06

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='tactic_description',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tactic',
            name='tactic_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tactic',
            name='tactic_name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
