# Generated by Django 4.2.1 on 2023-05-19 06:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0002_tactic_tactic_description_alter_tactic_tactic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='tactic_description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
