# Generated by Django 4.2.1 on 2023-05-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0003_alter_tactic_tactic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='tactic_name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
