# Generated by Django 4.2.1 on 2023-05-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0004_alter_tactic_tactic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tactic',
            options={'ordering': ['tactic_id']},
        ),
    ]
