# Generated by Django 4.2.1 on 2023-05-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technique',
            options={'ordering': ['technique_id']},
        ),
        migrations.AlterField(
            model_name='technique',
            name='technique_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
