# Generated by Django 4.2.1 on 2023-05-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0002_alter_technique_options_and_more'),
    ]

    operations = [
    ]
