# Generated by Django 4.2.1 on 2023-05-19 05:14

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdversaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField(unique=True, verbose_name='Group ID')),
                ('group_name', models.TextField(verbose_name='Group Name')),
                ('group_description', django_quill.fields.QuillField()),
            ],
            options={
                'verbose_name': 'Adversary Group',
                'verbose_name_plural': 'Adversary Groups',
            },
        ),
    ]
