# Generated by Django 4.2.1 on 2023-05-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adversary_groups', '0002_alter_adversarygroup_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversarygroup',
            name='associated_groups',
            field=models.TextField(blank=True, null=True, verbose_name='Associated Groups'),
        ),
    ]
