# Generated by Django 4.2.1 on 2023-05-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adversary_groups', '0003_adversarygroup_associated_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adversarygroup',
            options={'ordering': ['group_name', 'group_id'], 'verbose_name': 'Adversary Group', 'verbose_name_plural': 'Adversary Groups'},
        ),
    ]
