# Generated by Django 4.2.1 on 2023-05-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adversary_groups', '0004_alter_adversarygroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adversarygroup',
            options={'ordering': ['group_name'], 'verbose_name': 'Adversary Group', 'verbose_name_plural': 'Adversary Groups'},
        ),
    ]
