# Generated by Django 4.2.1 on 2023-05-19 06:06

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adversary_groups', '0006_alter_adversarygroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adversarygroup',
            name='group_description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adversarygroup',
            name='group_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adversarygroup',
            name='group_name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
