# Generated by Django 4.2.1 on 2023-05-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_techniques', '0001_initial'),
        ('tactics', '0001_initial'),
        ('adversary_groups', '0001_initial'),
        ('techniques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdversaryTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.PositiveBigIntegerField(default=1, unique=True)),
                ('adversary_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adversary_groups.adversarygroup')),
                ('sub_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_techniques.subtechnique')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactics.tactic')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techniques.technique')),
            ],
        ),
    ]
