# Generated by Django 4.2.1 on 2023-05-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_techniques', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtechnique',
            options={'verbose_name': 'Sub Technique', 'verbose_name_plural': 'Sub Techniques'},
        ),
    ]
