# Generated by Django 4.2.1 on 2023-05-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_techniques', '0002_alter_subtechnique_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtechnique',
            old_name='technique',
            new_name='techniques',
        ),
    ]
