# Generated by Django 4.2.1 on 2023-05-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_techniques', '0003_rename_technique_subtechnique_techniques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtechnique',
            old_name='techniques',
            new_name='technique',
        ),
    ]
