# Generated by Django 4.2.1 on 2023-05-22 07:11

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_techniques', '0005_alter_subtechnique_subtechnique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtechnique',
            name='subtechnique_description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
