# Generated by Django 4.2.1 on 2023-05-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_techniques', '0006_subtechnique_subtechnique_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtechnique',
            name='subtechnique_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
