# Generated by Django 4.2.1 on 2023-05-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adversary_groups', '0007_alter_adversarygroup_group_description_and_more'),
        ('sub_techniques', '0001_initial'),
        ('techniques', '0001_initial'),
        ('tactics', '0003_alter_tactic_tactic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdversaryGroupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversary_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adversary_groups.adversarygroup')),
                ('subtechniques', models.ManyToManyField(blank=True, to='sub_techniques.subtechnique')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactics.tactic')),
                ('techniques', models.ManyToManyField(to='techniques.technique')),
            ],
        ),
    ]
