# Generated by Django 4.2.1 on 2023-05-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_techniques', '0001_initial'),
        ('techniques', '0001_initial'),
        ('adversary_preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adversarygrouppreference',
            old_name='tactic',
            new_name='tactics',
        ),
        migrations.AlterField(
            model_name='adversarygrouppreference',
            name='subtechniques',
            field=models.ManyToManyField(blank=True, limit_choices_to={'technique__in': models.ManyToManyField(limit_choices_to={'tactics__in': [models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactics.tactic')]}, to='techniques.technique')}, to='sub_techniques.subtechnique'),
        ),
        migrations.AlterField(
            model_name='adversarygrouppreference',
            name='techniques',
            field=models.ManyToManyField(limit_choices_to={'tactics__in': [models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactics.tactic')]}, to='techniques.technique'),
        ),
    ]
