# Generated by Django 4.2.1 on 2023-05-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_techniques', '0007_alter_subtechnique_subtechnique_id'),
        ('techniques', '0003_auto_20230522_0659'),
        ('adversary_preferences', '0002_rename_tactic_adversarygrouppreference_tactics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adversarygrouppreference',
            old_name='tactics',
            new_name='tactic',
        ),
        migrations.RemoveField(
            model_name='adversarygrouppreference',
            name='techniques',
        ),
        migrations.AddField(
            model_name='adversarygrouppreference',
            name='technique',
            field=models.ForeignKey(default='', limit_choices_to={'tactic': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactics.tactic')}, on_delete=django.db.models.deletion.CASCADE, to='techniques.technique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adversarygrouppreference',
            name='subtechniques',
            field=models.ManyToManyField(blank=True, to='sub_techniques.subtechnique'),
        ),
    ]
