# Generated by Django 4.2.1 on 2023-05-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0003_auto_20230522_0659'),
        ('adversary_preferences', '0003_rename_tactics_adversarygrouppreference_tactic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adversarygrouppreference',
            name='technique',
            field=models.ForeignKey(limit_choices_to={'tactics': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tactics.tactic')}, on_delete=django.db.models.deletion.CASCADE, to='techniques.technique'),
        ),
    ]
